const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, 'public', 'index.html');
const L = [];
function a(){ for(let i=0;i<arguments.length;i++) L.push(arguments[i]); }
a('<!DOCTYPE html>','<html lang="zh-CN">','<head>','<meta charset="UTF-8">','<meta name="viewport" content="width=device-width,initial-scale=1.0">','<title>Flip7 \u7ffb\u8f6c\u724c</title>','<style>');
a('*{margin:0;padding:0;box-sizing:border-box}');
a(':root{--pri:#6c5ce7;--pri2:#a29bfe;--red:#e74c3c;--grn:#27ae60;--ylw:#f39c12;--bg:#1a1a2e;--bg2:#16213e;--bg3:#0f3460;--txt:#eee;--dim:#aaa;--r:12px}');
a('body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--txt);min-height:100vh;overflow-x:hidden}');
a('.scr{display:none;min-height:100vh;padding:20px;padding-top:48px;animation:fi .3s}.scr.act{display:flex;flex-direction:column;align-items:center}');
a('@keyframes fi{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}@keyframes su{from{transform:translateY(20px);opacity:0}to{transform:translateY(0);opacity:1}}');
a('.btn{padding:12px 28px;border:none;border-radius:var(--r);font-size:16px;font-weight:600;cursor:pointer;transition:all .2s}.btn:active{transform:scale(.95)}.btn:disabled{opacity:.4;cursor:not-allowed}');
a('.bp{background:var(--pri);color:#fff}.bp:hover{background:var(--pri2)}.bd{background:var(--red);color:#fff}.bs{background:var(--grn);color:#fff}.bw{background:var(--ylw);color:#fff}.bo{background:0 0;border:2px solid var(--pri);color:var(--pri)}.bl{padding:16px 40px;font-size:18px}');
a('.logo{font-size:48px;font-weight:900;background:linear-gradient(135deg,var(--pri),var(--ylw));-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.sub{color:var(--dim);font-size:16px;margin-top:8px}');
a('#lobby{justify-content:center;text-align:center;gap:20px}.lobby-box{background:var(--bg2);border-radius:var(--r);padding:20px;max-width:420px;width:100%;text-align:left;margin:0 auto}');
a('.lobby-box h3{color:var(--pri2);margin-bottom:10px}.seat-list{list-style:none;margin:10px 0}.seat-list li{padding:8px 12px;border-bottom:1px solid var(--bg3)}.seat-list li.me{background:var(--bg3);border-radius:8px}');
a('.join-area{display:flex;gap:10px;margin-top:10px}.join-area input{flex:1;padding:10px 14px;border-radius:var(--r);border:2px solid var(--bg3);background:var(--bg2);color:var(--txt);font-size:16px;outline:none}');
a('.rs-row{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin:12px 0}.rs-row button{width:40px;height:40px;border-radius:8px;border:2px solid var(--bg3);background:var(--bg2);color:var(--txt);font-weight:700;cursor:pointer}.rs-row button.sel{border-color:var(--pri);background:var(--pri)}');
a('.host-only{display:none}.host-only.show{display:block}#hostEnd.host-only.show{display:flex;gap:12px;flex-wrap:wrap;justify-content:center}');
a('#game{padding:10px;gap:8px}.ghdr{width:100%;max-width:700px;display:flex;justify-content:space-between;align-items:center;background:var(--bg2);border-radius:var(--r);padding:10px 16px;font-size:13px}');
a('.ghdr .gi{display:flex;flex-direction:column;align-items:center;gap:2px}.ghdr .gl2{color:var(--dim);font-size:11px}.ghdr .gv{font-weight:700}');
a('.players-area{width:100%;max-width:700px;display:flex;flex-wrap:wrap;gap:8px;justify-content:center}');
a('.player-box{flex:1;min-width:140px;max-width:220px;background:var(--bg2);border-radius:var(--r);padding:12px;border:2px solid transparent;transition:all .2s}');
a('.player-box.current{border-color:var(--pri);box-shadow:0 0 15px rgba(108,92,231,.4)}.player-box.stayed{border-color:var(--grn);opacity:.7}.player-box.busted{border-color:var(--red);opacity:.5}.player-box.me{background:var(--bg3)}');
a('.player-box .pname{font-size:13px;font-weight:700;margin-bottom:4px}.player-box .pscore{font-size:11px;color:var(--dim);margin-bottom:6px}');
a('.player-box .pcards{display:flex;flex-wrap:wrap;gap:4px;min-height:40px}.player-box .ptags{display:flex;gap:4px;flex-wrap:wrap;margin-top:4px}');
a('.cd{width:36px;height:50px;border-radius:6px;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:12px;box-shadow:0 1px 4px rgba(0,0,0,.2);animation:su .3s}');
a('.cn{background:#fff;color:#333}.cb{background:linear-gradient(135deg,#f8e71c,#f5a623);color:#333}.ca{color:#fff;font-size:9px;text-align:center;line-height:1.1;padding:2px}');
a('.ca.fr{background:linear-gradient(135deg,#74b9ff,#0984e3)}.ca.f3{background:linear-gradient(135deg,#fd79a8,#e84393)}.ca.sf{background:linear-gradient(135deg,#55efc4,#00b894)}');
a('.tg{padding:2px 6px;border-radius:4px;font-size:9px;font-weight:600}.tg.bonus{background:rgba(245,166,35,.2);color:var(--ylw)}.tg.safe{background:rgba(39,174,96,.2);color:var(--grn)}');
a('.tg.status-stayed{background:rgba(39,174,96,.15);color:var(--grn)}.tg.status-busted{background:rgba(231,76,60,.15);color:var(--red)}');
a('.aa{width:100%;max-width:700px;display:flex;gap:12px;justify-content:center;flex-wrap:wrap;padding:8px 0}.turn-info{width:100%;max-width:700px;background:var(--bg3);border-radius:var(--r);padding:10px 16px;text-align:center;font-size:14px;font-weight:600}.turn-info .highlight{color:var(--ylw)}');
a('.ov{position:fixed;top:0;left:0;right:0;bottom:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:20px;z-index:100;background:rgba(0,0,0,.85)}.ov h3{font-size:20px}.tl{display:flex;flex-wrap:wrap;gap:12px;justify-content:center}.tb{padding:14px 20px;border-radius:var(--r);background:var(--bg2);border:2px solid var(--bg3);color:var(--txt);font-size:15px;cursor:pointer}.tb:hover{border-color:var(--pri)}');
a('.glog{width:100%;max-width:700px;background:var(--bg2);border-radius:var(--r);padding:10px;max-height:160px;overflow-y:auto}.le{font-size:11px;color:var(--dim);padding:2px 0}.le.ex{color:var(--red)}.le.ok{color:var(--grn)}.le.ac{color:var(--pri2)}');
a('.result-scr{justify-content:center;gap:20px;text-align:center}.rt{width:100%;max-width:500px;border-collapse:collapse}.rt th,.rt td{padding:10px 12px;text-align:center;border-bottom:1px solid var(--bg3)}.rt th{color:var(--dim);font-size:13px}.rt .br{color:var(--red);opacity:.7}.rt .wr{color:var(--ylw);font-weight:700}.rt .fr{color:var(--grn);font-weight:700}');
a('.ftit{font-size:28px;font-weight:700;color:var(--ylw)}.bc{font-size:13px}.bc.pos{color:var(--grn)}.bc.neg{color:var(--red)}');
a('.spec-bar{display:none;background:var(--ylw);color:#333;text-align:center;padding:8px;font-weight:700;font-size:14px;position:fixed;top:0;left:0;right:0;z-index:50}.spec-bar.show{display:block}');
a('#toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:var(--bg3);padding:12px 24px;border-radius:var(--r);z-index:200;display:none;max-width:90%}#toast.show{display:block}');
a('.conn{color:var(--dim);font-size:13px}');
a('</style></head><body>');
a('<div id="specBar" class="spec-bar">\u89c2\u6218\u4e2d \u2014 \u6e38\u620f\u8fdb\u884c\u4e2d\uff0c\u8bf7\u7b49\u5f85\u672c\u5c40\u7ed3\u675f\u540e\u52a0\u5165</div>');
a('<div id="toast"></div>');
a('<section id="lobby" class="scr act">','<div class="logo">Flip7</div>','<p class="sub">\u591a\u4eba\u8054\u673a \u7ffb\u8f6c\u724c</p>','<p id="connSt" class="conn">\u8fde\u63a5\u4e2d\u2026</p>');
a('<div class="lobby-box"><h3>\u73a9\u5bb6\u5217\u8868 (<span id="seatCnt">0</span>/<span id="roomMax">4</span>)</h3><ul id="seatList" class="seat-list"></ul>');
a('<div id="joinBlock"><div class="join-area"><input id="nameIn" maxlength="12" placeholder="\u8f93\u5165\u6635\u79f0"><button class="btn bp" id="btnJoin">\u52a0\u5165</button></div></div>');
a('<div id="hostLobby" class="host-only"><h3 style="margin-top:16px">\u623f\u95f4\u4eba\u6570</h3><div id="rsBtns" class="rs-row"></div><button class="btn bl bp" id="btnStart" style="margin-top:16px;width:100%">\u5f00\u59cb\u6e38\u620f</button></div>');
a('</div></section>');
a('<section id="game" class="scr"><div id="gh" class="ghdr"></div><div id="ti" class="turn-info"></div><div id="pa" class="players-area"></div><div id="aa" class="aa"></div><div id="glog" class="glog"></div></section>');
a('<section id="roundEnd" class="scr result-scr"><h2 class="ftit" id="ret"></h2><table class="rt" id="rrt"></table>');
a('<div id="hostRound" class="host-only"><button class="btn bp bl" id="btnNext">\u4e0b\u4e00\u56de\u5408</button></div></section>');
a('<section id="gameEnd" class="scr result-scr"><h2 class="ftit" id="wn"></h2><p id="ws" class="sub"></p><table class="rt" id="frt"></table>');
a('<div id="hostEnd" class="host-only">');
a('<button class="btn bp bl" id="btnRestart">\u91cd\u65b0\u5f00\u59cb</button><button class="btn bo bl" id="btnLobby">\u8fd4\u56de\u5927\u5385</button></div></section>');
a('<div id="tov" class="ov" style="display:none"><h3 id="tovT"></h3><div id="tovL" class="tl"></div></div>');
a('<script>');
a('(function(){');
a('var WIN=200,ANTE=100,MAXR=3;');
a('var ws,mySeat=-1,hostSeat=0,roomSize=4,seats=[],G=null;');
a('var selRoom=4;');
a('function $(id){return document.getElementById(id)}');
a('function send(o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o))}');
a('function showScr(id){document.querySelectorAll(".scr").forEach(function(s){s.classList.remove("act")});var el=$(id);if(el)el.classList.add("act")}');
a('function toast(t){var el=$("toast");el.textContent=t;el.classList.add("show");setTimeout(function(){el.classList.remove("show")},2800)}');
a('function isHost(){return mySeat===hostSeat&&mySeat>=0}');
a('function cname(c){if(c.t==="n")return String(c.v);if(c.t==="b")return c.v;return{freeze:"\\u51bb\\u7ed3",flip3:"\\u7ffb\\u4e09\\u5f20",safety:"\\u5b89\\u5168\\u724c"}[c.v]}');
a('function calcLive(p){if(p.status==="busted")return 0;var ns=0,m=1,ba=0;p.hand.forEach(function(c){if(c.t==="n")ns+=c.v});p.bonus.forEach(function(b){if(b.v==="x2")m*=2;else ba+=parseInt(b.v,10)});return ns*m+ba}');
a('function rcard(c){if(c.xx)return\'<div class="cd cn" style="border:2px solid var(--red)">\'+c.v+"</div>";if(c.t==="n")return\'<div class="cd cn">\'+c.v+"</div>";if(c.t==="b")return\'<div class="cd cb">\'+c.v+"</div>";var sc=c.v==="freeze"?"fr":c.v==="flip3"?"f3":"sf";return\'<div class="cd ca \'+sc+\'">\'+cname(c)+"</div>"}');
a('function buildRs(){var h="";for(var n=2;n<=12;n++)h+=\'<button type="button" data-n="\'+n+\'" class="\'+(n===selRoom?"sel":"")+\'">\'+n+"</button>";$("rsBtns").innerHTML=h;$("rsBtns").querySelectorAll("button").forEach(function(b){b.onclick=function(){selRoom=parseInt(b.dataset.n,10);buildRs();if(isHost())send({type:"setRoomSize",size:selRoom})}})}');
a('buildRs();');
a('function renderLobby(){$("roomMax").textContent=roomSize;selRoom=roomSize;$("seatCnt").textContent=seats.length;var ul=$("seatList");ul.innerHTML="";seats.forEach(function(s,i){var li=document.createElement("li");if(i===mySeat)li.classList.add("me");var pre=(s.ai?"\\ud83e\\udd16 ":"")+(i===hostSeat?"\\ud83d\\udc51 ":"");li.textContent=pre+s.name;ul.appendChild(li)});var joined=mySeat>=0;$("joinBlock").style.display=joined?"none":"block";var hh=isHost()&&G&&G.phase==="lobby";$("hostLobby").classList.toggle("show",!!hh);$("btnStart").disabled=!joined||seats.length<1}');
a('function renderGame(){if(!G)return;var pot=G.players.length*ANTE*G.mult;$("gh").innerHTML=\'<div class="gi"><span class="gl2">\\u724c\\u5806</span><span class="gv">\'+G.deck.length+\'\\u5f20</span></div><div class="gi"><span class="gl2">\\u5e95\\u6ce8</span><span class="gv">\'+ANTE+\'\\u8c46</span></div><div class="gi"><span class="gl2">\\u5956\\u6c60</span><span class="gv">\'+pot+\'\\u8c46</span></div><div class="gi"><span class="gl2">\\u52a0\\u6ce8</span><span class="gv">x\'+G.mult+\'</span></div><div class="gi"><span class="gl2">\\u56de\\u5408</span><span class="gv">\'+G.round+\'</span></div>\';');
a('var ti="";if(G.phase==="raise")ti="\\ud83c\\udccf <span class=\\"highlight\\">"+esc(G.players[G.dealer].name)+"</span> \\u662f\\u5e84\\u5bb6\\uff0c\\u662f\\u5426\\u52a0\\u6ce8\uff1f";');
a('else if(G.f3r>0&&G.f3t>=0)ti="\\ud83c\\udccf <span class=\\"highlight\\">"+esc(G.players[G.f3t].name)+"</span> \\u88ab\\u5f3a\\u5236\\u7ffb\\u724c\\uff08\\u5269 "+G.f3r+" \\u5f20\\uff09";');
a('else if(G.phase==="playing")ti="\\u27a1 \\u8f6e\\u5230 <span class=\\"highlight\\">"+esc(G.players[G.cur].name)+(G.cur===mySeat?" (\\u4f60)":"")+"</span>";$("ti").innerHTML=ti;');
a('var pa="";G.players.forEach(function(pl,i){var cls="player-box";if(i===G.cur&&G.phase==="playing")cls+=" current";if(pl.status==="stayed")cls+=" stayed";if(pl.status==="busted")cls+=" busted";if(i===mySeat)cls+=" me";');
a('var nm=esc(pl.name);if(i===hostSeat&&seats[i]&&!seats[i].ai)nm="\\ud83d\\udc51 "+nm;else if(seats[i]&&seats[i].ai)nm="\\ud83e\\udd16 "+nm;if(i===G.cur&&G.phase==="playing"&&i===mySeat)nm+=" (\\u4f60)";');
a('pa+=\'<div class="\'+cls+\'"><div class="pname">\'+nm+\'</div><div class="pscore"><b>\\u5c40\\u9762:\'+calcLive(pl)+\'</b> | \\u7d2f\\u8ba1:\'+pl.total+\' | \\ud83e\\uded8\'+pl.beans+\'</div><div class="pcards">\';pl.hand.forEach(function(c){pa+=rcard(c)});if(!pl.hand.length&&pl.status==="active")pa+=\'<span style="color:var(--dim);font-size:10px">\\u7a7a</span>\';pa+=\'</div><div class="ptags">\';');
a('pl.bonus.forEach(function(b){pa+=\'<span class="tg bonus">\'+b.v+"</span>"});if(pl.safe)pa+=\'<span class="tg safe">\\u5b89\\u5168</span>\';if(pl.status==="stayed")pa+=\'<span class="tg status-stayed">\\u5df2\\u505c</span>\';if(pl.status==="busted")pa+=\'<span class="tg status-busted">\\u7206\\u70b8</span>\';pa+=\'</div></div>\'});$("pa").innerHTML=pa;');
a('var aa="";if(G.targetPending&&mySeat===G.targetPending.from){$("tov").style.display="flex";var card=G.targetPending.card;$("tovT").textContent="\\u9009\\u62e9\\u76ee\\u6807\\uff1a"+cname(card);var tl="";G.targetPending.targets.forEach(function(t){tl+=\'<button type="button" class="tb" data-idx="\'+t.idx+\'">\'+esc(t.name)+"</button>"});$("tovL").innerHTML=tl;$("tovL").querySelectorAll(".tb").forEach(function(b){b.onclick=function(){send({type:"target",idx:parseInt(b.dataset.idx,10)});$("tov").style.display="none"}})}else{$("tov").style.display="none"}');
a('if(G.phase==="raise"&&mySeat===G.dealer){aa=\'<button class="btn bw" id="aRaise">\\u52a0\\u6ce8 (x\'+G.mult+"\\u2192x"+G.mult*2+\')</button><button class="btn bo" id="aSkip">\\u4e0d\\u52a0\\u6ce8\\uff0c\\u5f00\\u59cb</button>\'}');
a('else if(G.phase==="playing"&&G.f3r>0)aa=\'<span style="color:var(--ylw)">\\u7ffb\\u4e09\\u5f20\\u6267\\u884c\\u4e2d\u2026</span>\';');
a('else if(G.phase==="playing"&&mySeat===G.cur&&G.players[G.cur].status==="active"){var cs=G.players[G.cur].hand.length>0;aa=\'<button class="btn bp" id="aHit">\\u8981\\u724c</button><button class="btn bs" id="aStay"\'+(cs?"":\' disabled\')+\'>\\u505c\\u724c</button>\'}');
a('$("aa").innerHTML=aa;var rh=$("aRaise");if(rh)rh.onclick=function(){send({type:"raise"})};var sk=$("aSkip");if(sk)sk.onclick=function(){send({type:"skip"})};var hi=$("aHit");if(hi)hi.onclick=function(){send({type:"hit"})};var st=$("aStay");if(st)st.onclick=function(){send({type:"stay"})};');
a('var lg="";(G.log||[]).forEach(function(l){lg+=\'<div class="le \'+(l.cls||"")+\'">\'+esc(l.t)+"</div>"});var gl=$("glog");gl.innerHTML=lg;gl.scrollTop=gl.scrollHeight}');
a('function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}');
a('function renderRoundEnd(){if(!G)return;var f7=G.f7winner;var h="<thead><tr><th>\\u73a9\\u5bb6</th><th>\\u72b6\\u6001</th><th>\\u672c\\u56de\\u5408</th><th>\\u7d2f\\u8ba1</th></tr></thead><tbody>";');
a('var sorted=G.players.slice().sort(function(a,b){return b.rscore-a.rscore});sorted.forEach(function(p){var idx=G.players.indexOf(p);var cls="",st="\\u505c\\u724c";if(p.status==="busted"){cls="br";st="\\u7206\\u70b8"}if(idx===f7){cls="fr";st="Flip7!"}h+=\'<tr class="\'+cls+\'"><td>\'+esc(p.name)+\'</td><td>\'+st+\'</td><td>+\'+p.rscore+\'</td><td>\'+p.total+"</td></tr>"});h+="</tbody>";$("rrt").innerHTML=h;$("ret").textContent="\\u7b2c "+G.round+" \\u56de\\u5408\\u7ed3\\u675f";$("hostRound").classList.toggle("show",isHost())}');
a('function renderGameEnd(){if(!G||!G.finalRanking)return;var w=G.finalRanking[0];$("wn").textContent=esc(w.name)+" \\u80dc\\u5229!";$("ws").textContent="\\u603b\\u5206 "+w.total+" \\u5206";var h="<thead><tr><th>#</th><th>\\u73a9\\u5bb6</th><th>\\u603b\\u5206</th><th>\\u8c46\\u5b50</th></tr></thead><tbody>";');
a('G.finalRanking.forEach(function(p,i){var cls=i===0?"wr":"",ct=p._bc>=0?"+"+p._bc:""+p._bc,cc=p._bc>=0?"pos":"neg";h+=\'<tr class="\'+cls+\'"><td>\'+(i+1)+\'</td><td>\'+esc(p.name)+\'</td><td>\'+p.total+\'</td><td><span class="bc \'+cc+\'">\'+ct+\'</span> (\\u5269 \'+p.beans+")</td></tr>"});h+="</tbody>";$("frt").innerHTML=h;$("hostEnd").classList.toggle("show",isHost())}');
a('function onState(msg){G=msg.G;seats=msg.seats||[];roomSize=msg.roomSize||4;hostSeat=msg.hostSeat!=null?msg.hostSeat:0;selRoom=roomSize;$("roomMax").textContent=roomSize;buildRs();');
a('var spec=mySeat<0&&G.phase!=="lobby";$("specBar").classList.toggle("show",spec);document.querySelectorAll(".scr").forEach(function(s){s.style.paddingTop=spec?"48px":"20px"});');
a('if(G.phase==="lobby"){showScr("lobby");renderLobby()}else if(G.phase==="roundEnd"){showScr("roundEnd");renderRoundEnd();renderGame()}else if(G.phase==="gameEnd"){showScr("gameEnd");renderGameEnd()}else{showScr("game");renderGame()}renderLobby()}');
a('function connect(){var proto=location.protocol==="https:"?"wss:":"ws:";ws=new WebSocket(proto+"//"+location.host);$("connSt").textContent="\\u8fde\\u63a5\\u4e2d\u2026";ws.onopen=function(){$("connSt").textContent="\\u5df2\\u8fde\\u63a5"};ws.onclose=function(){$("connSt").textContent="\\u5df2\\u65ad\\u5f00\\uff0c3\\u79d2\\u540e\\u91cd\\u8fde\u2026";setTimeout(connect,3000)};ws.onmessage=function(ev){var msg;try{msg=JSON.parse(ev.data)}catch(e){return}if(msg.type==="state")onState(msg);else if(msg.type==="seated")mySeat=msg.seat;else if(msg.type==="info")toast(msg.text)}}');
a('$("btnJoin").onclick=function(){var n=$("nameIn").value.trim();if(!n){toast("\\u8bf7\\u8f93\\u5165\\u6635\\u79f0");return}send({type:"join",name:n})};');
a('$("btnStart").onclick=function(){send({type:"start"})};$("btnNext").onclick=function(){send({type:"nextRound"})};$("btnRestart").onclick=function(){send({type:"restart"})};$("btnLobby").onclick=function(){send({type:"backToLobby"})};');
a('connect();})();');
a('</script></body></html>');
fs.writeFileSync(out, L.join('\n'), 'utf8');
console.log('Wrote', out, 'bytes:', fs.statSync(out).size);

